# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .cluster import *
from .provider import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "aws-quickstart-redshift",
  "mod": "index",
  "fqn": "pulumi_aws_quickstart_redshift",
  "classes": {
   "aws-quickstart-redshift:index:Cluster": "Cluster"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "aws-quickstart-redshift",
  "token": "pulumi:providers:aws-quickstart-redshift",
  "fqn": "pulumi_aws_quickstart_redshift",
  "class": "Provider"
 }
]
"""
)
